##
##	Created by Benjamin.
##	benjamin.dupuis@epitech.eu
##

all:
				make -C client
				make -C server

clean:
				make clean -C client
				make clean -C server

fclean:			clean
				make fclean -C client
				make fclean -C server

re:				fclean all



